name: jhub_docs
channels:
  - conda-forge
dependencies:
- nodejs
- python=3.6
- alembic
- jinja2
- pamela
- requests
- sqlalchemy>=1
- tornado>=5.0
- traitlets>=4.1
- sphinx>=1.7
- pip:
  - python-oauth2
  - recommonmark==0.4.0
  - async_generator
  - prometheus_client
